[package]
name = "oxiedraw-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
oxiedraw-core.workspace = true
oxiedraw-utils.workspace = true

relm4.workspace = true
relm4-components.workspace = true
gtk.workspace = true
adw.workspace = true

tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
