[package]
name = "oxiedraw-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
oxiedraw-utils.workspace = true

ash.workspace = true
gpu-allocator.workspace = true

cosmic-text.workspace = true

thiserror.workspace = true
tracing.workspace = true

serde = { workspace = true }
serde_json = { workspace = true }
tar = { workspace = true }
png = { workspace = true }
jpeg-encoder = { workspace = true }
image = { workspace = true }
ravif = { workspace = true }
rgb = { workspace = true }
